# Generated by Django 3.1.7 on 2021-05-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDetail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
