# Generated by Django 3.1.7 on 2021-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210530_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
