# Generated by Django 3.1.7 on 2021-06-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modeltype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
